config/routes.rb
Rails.application.routes.draw do
  get 'song', to: 'songs#index'
  resources :songs
  resources :albums
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "albums#index"
end

app/models/album.rb
class Album < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: %i[ show edit update destroy ]

  # GET /albums or /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1 or /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums or /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to album_url(@album), notice: "Album was successfully created." }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1 or /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to album_url(@album), notice: "Album was successfully updated." }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1 or /albums/1.json
  def destroy
    @album.destroy

    respond_to do |format|
      format.html { redirect_to albums_url, notice: "Album was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def album_params
      params.require(:album).permit(:loves, :likes, :artist, :name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: %i[ show edit update destroy ]

  # GET /songs or /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1 or /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs or /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to song_url(@song), notice: "Song was successfully created." }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1 or /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to song_url(@song), notice: "Song was successfully updated." }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1 or /songs/1.json
  def destroy
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url, notice: "Song was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:name, :album_id, :loves, :likes)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/albums/_album.html.erb
<div id="<%= dom_id album %>">
  <p>
    <strong>Loves:</strong>
    <%= album.loves %>
  </p>

  <p>
    <strong>Likes:</strong>
    <%= album.likes %>
  </p>

  <p>
    <strong>Artist:</strong>
    <%= album.artist %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= album.name %>
  </p>

</div>

app/views/albums/_form.html.erb
<%= form_with(model: album) do |form| %>
  <% if album.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
        <% album.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :loves, style: "display: block" %>
    <%= form.number_field :loves %>
  </div>

  <div>
    <%= form.label :likes, style: "display: block" %>
    <%= form.number_field :likes %>
  </div>

  <div>
    <%= form.label :artist, style: "display: block" %>
    <%= form.text_field :artist %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing album</h1>

<%= render "form", album: @album %>

<br>

<div>
  <%= link_to "Show this album", @album %> |
  <%= link_to "Back to albums", albums_path %>
</div>

app/views/albums/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Taylor Swift</h1>

<div id="albums">
  <% @albums.each do |album| %>
    <%= render album %>
    <p>
      <%= link_to "Show this album", "song"%>
    </p>
  <% end %>
</div>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render "form", album: @album %>

<br>

<div>
  <%= link_to "Back to albums", albums_path %>
</div>

app/views/albums/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @album %>
<%= render @songs %>

<div>

<p style="color: green"><%= notice %></p>

<h1>Songs</h1>

<div id="songs">
  <% @songs.each do |song| %>
    <%= render song %>
    <p>
      <%= link_to "Show this song", song %>
    </p>
  <% end %>
</div>

<%= link_to "New song", new_song_path %>
  <%= link_to "Edit this album", edit_album_path(@album) %> |
  <%= link_to "Back to albums", albums_path %>

  <%= button_to "Destroy this album", @album, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <form action="/" float="left">
    <input type="submit" value="Home" />
    </form>    
    <%= yield %>
  </body>
</html>

app/views/songs/_form.html.erb
<%= form_with(model: song) do |form| %>
  <% if song.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
        <% song.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :album_id, style: "display: block" %>
    <%= form.text_field :album_id %>
  </div>

  <div>
    <%= form.label :loves, style: "display: block" %>
    <%= form.number_field :loves %>
  </div>

  <div>
    <%= form.label :likes, style: "display: block" %>
    <%= form.number_field :likes %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/songs/_song.html.erb
<div id="<%= dom_id song %>">
  <p>
    <strong>Name:</strong>
    <%= song.name %>
  </p>

  <p>
    <strong>Album:</strong>
    <%= song.album_id %>
  </p>

  <p>
    <strong>Loves:</strong>
    <%= song.loves %>
  </p>

  <p>
    <strong>Likes:</strong>
    <%= song.likes %>
  </p>

</div>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render "form", song: @song %>

<br>

<div>
  <%= link_to "Show this song", @song %> |
  <%= link_to "Back to songs", songs_path %>
</div>

app/views/songs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Songs</h1>

<div id="songs">
  <% @songs.each do |song| %>
    <%= render song %>
    <div>---------------------</div>
  <% end %>
</div>

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render "form", song: @song %>

<br>

<div>
  <%= link_to "Back to songs", songs_path %>
</div>

app/views/songs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @song %>

<div>
  <%= link_to "Edit this song", edit_song_path(@song) %> |
  <%= link_to "Back to songs", songs_path %>

  <%= button_to "Destroy this song", @song, method: :delete %>
</div>